config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'registrations#index'
  get '/login', to: 'registrations#login'
  post '/login', to: 'registrations#connexion'
  resources :registrations
  resources :gossip
  resources :like
  resources :comment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
    belongs_to :user
    belongs_to :commenteable, polymorphic: true
    has_many :likes, as: :likeable
    has_many :childs, class_name: "Comment", as: :commenteable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :likeable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :gossips
    has_many :likes
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
    def index
        @comments = Commentaire.all
    end

    def new
        puts "new"
        puts params
        @comments = Commentaire.new
    end

    def create
        puts "create"
        puts session[:current_user_id]
        @comments = Commentaire.new
        
    end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
    
    def index
        puts "index"
        @gossips = Gossip.all
        
    end

    def show
        puts "show"
        @gossips = Gossip.all
        
    end

    def new
    puts "new"
      @gossip = Gossip.find_by(user: session[:current_user_id])
    end

    def create
        puts "create"
        @gossip = Gossip.new
        @gossip.title = params[:title]
        @gossip.content = params[:content]
        @gossip.user = User.find(session[:current_user_id])
        @gossip.save
        redirect_to gossip_index_path
    end

    def destroy
        puts "des"
        puts params
        @gossip = Gossip.find_by(user: session[:current_user_id])
        @gossip.destroy
        redirect_to gossip_path
    end

end

app/controllers/like_controller.rb
class LikeController < ApplicationController
    def index
        @likes = Like.all
    end

    def new
        @like = Like.new
    end

    def create
        
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

    def index
        @gossips = Gossip.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new
        @user.name = params[:name]
        @user.email = params[:email]
        @user.password = params[:password]
        @user.save
        session[:current_user_id] = @user_email.id
        redirect_to(gossip_path(@user.id))
    end

    def login
    
    end

    def connexion
        @user_email = User.find_by(email: params[:email])
        @user_password = User.find_by(password: params[:password])
        if @user_email.email != params[:email] && @user_password.password != params[:password]
            redirect_to login_path
        else
            session[:current_user_id] = @user_email.id
            redirect_to gossip_path(@user_email.id)
        end

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commentaire_helper.rb
module CommentaireHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/comment/new.html.erb
<%= form_tag('/comment') do %>
            <h3 class ="mb-5">please subscribe</h3>
            <div class="row">
            <%= hidden_field_tag 'token'%>
                <div class="form-group">
                    <%= text_area_tag [:content], nil, placeholder: 'content', class: 'form-control' %>
                </div>
				<div class="form-group center">
                    <div><%= submit_tag 'Commenter' , class: "btn btn-primary mb-5"%>
                <div>
                </div>
            </div>
        <% end %>

app/views/gossip/index.html.erb
<% @gossips.each do |gossip| %>
        <div class="card row col-md-3 mb-4 mr-3" style="width: 18rem;">
        <div class="card-body">
        <p><%= gossip.title %></p>
        <h4>Content :</h4>
        <p><%= gossip.content %></p>
        <a href="<% gossip_index_path %>" class= "btn btn-lg btn-danger" data-confirm="êtes-vous sur?"
        data-method="DELETE">Supprimmer</a>
        <%= link_to "Like !", new_like_path, class: "btn btn-lg btn-primary" %><br>
        <%= link_to "comment !", new_comment_path, class: "btn btn-lg btn-primary" %><br>
        </div>
        </div>
<% end %>

app/views/gossip/new.html.erb
<%= form_tag('/gossip') do %>
            <h3 class ="mb-5">please subscribe</h3>
            <div class="row">
            <%= hidden_field_tag 'token'%>
            <div class="col-md-6">
                <div class="form-group">
                    <%= text_field_tag [:title], nil, placeholder: 'title', class: 'form-control'%>
                </div>
                <div class="form-group">
                    <%= text_area_tag [:content], nil, placeholder: 'content', class: 'form-control' %>
                </div>
				<div class="form-group center">
                    <div><%= submit_tag 'Creer' , class: "btn btn-primary mb-5"%>
                <div>
                </div>
            </div>
        <% end %>

app/views/gossip/show.html.erb
<div class = "container">
<%= link_to "Creer un gossip !", new_gossip_path, class: "btn btn-lg btn-primary" %><br>

<p>

</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_registration_path %>">Inscriptions</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= login_path %>">Connexion</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= gossip_index_path %>">Gossips</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
  </body>
</html>